baseURL = "https://teachdentistry.ctl.columbia.edu/"
metaDataFormat = "yaml"
languageCode = "en-us"
theme = "ctl-book"
title = "Teach Dentistry"
googleAnalytics = "G-77M2WMTF1R"

[params]
    customCSS = "main.css"
    description = "Teach Dentistry is a learning module that lets you explore the foundations of entering dental academics while charting your own path."
    keywords = "dental education, teach dentistry, medicine, dentistry"